on:
  push:
    paths: "**.rs"
  pull_request:
    paths: "**.rs"
  workflow_dispatch:

name: Linux Build

env:
  # This is required to enable the web_sys clipboard API which egui_web uses
  # https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.Clipboard.html
  # https://rustwasm.github.io/docs/wasm-bindgen/web-sys/unstable-apis.html
  RUSTFLAGS: --cfg=web_sys_unstable_apis
  CARGO_TERM_COLOR: always

jobs:
  linux_gnu_build:
    name: Linux GNU Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu
          override: true
      - name: Setup device_query dependencies
        run: sudo apt-get install libx11-dev
      - name: Setup rdev dependencies
        run: sudo apt-get --assume-yes install libxtst-dev libevdev-dev
      - name: Setup eframe dependencies
        run: sudo apt-get install libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libspeechd-dev libxkbcommon-dev libssl-dev
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --verbose --target x86_64-unknown-linux-gnu
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: rusty_autoclicker_linux
          path: target/x86_64-unknown-linux-gnu/release/rusty-autoclicker

